### ISSUE TITLE
Eu poderia usar este para React Native?

### ISSUE THREAD

**Issue by MichelDiz** [diegohaz/nod#17]
Poderia? Estou pensando em me aprofundar nessa coisa de criar módulos, pois tem muita coisa que não dá pra fazer ainda com módulos de terceiros. Por exemplo, queria usar o Firebase Auth UI - Mas só tem pra nativo, estou com documentação separada pra estudar como implementar código nativo com RN.

Mas ter um gerador de módulo seria interessante. Ajudaria muito.

Abraço!

**Comment by diegohaz** [comment]
Fala, Michel.

Eu nunca fiz nada pra React Native, mas, se for node, você consegue, sim. Talvez com apenas alguns ajustes.

Dá uma olhada na seção [Built with Nod](https://github.com/diegohaz/nod#built-with-nod) pra ver se você acha algo feito de forma similar ao que você quer fazer. Se conseguir, adiciona o seu lá pra ajudar a galera que quiser fazer algo pra React Native também.

Se o Nod não for útil, tenta usar o https://github.com/sindresorhus/generator-nm, que é um pouco mais genérico.

**Comment by MichelDiz** [comment]
@diegohaz Blz, eu estava olhando outros repositórios teus - Aquele gerador de API é interessante, sabe me dizer se o restify é melhor que o Express? Estava lendo muito sobre API's em node e vi muita gente falando bem do Restify.

**Comment by diegohaz** [comment]
Eu apenas experimentei o restify. Não fui muito a fundo. Pra fazer uma RESTful API ele deve ser melhor. Numa futura versão do `rest` talvez eu dê uma chance pra ele, mas o express resolve o problema muito bem também.

A única coisa que eu sinto muita falta é de escrever middlewares com `async`/`await`, mas parece que isso vai ser possível em breve no express.

**Comment by MichelDiz** [comment]
PS; Obrigado pelas dicas!
